In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/raw/hotel_bookings_updated_2024.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
 32  city                            119390 non-null  str
dtypes: float64(4), int64(16), str(13)
memory usage: 30.1 MB

In [4]:
print("\n Unique values:")
for col in df.columns:
    unique_vals = df[col].unique()
    if len(unique_vals) <= 20:
        values_str = " ".join(str(v) for v in unique_vals)
        print(f"{col} => {values_str}")
    else:
        print(f"{col} => Too many unique values ({df[col].nunique()})")

 Unique values:
hotel => Too many unique values (30)
is_canceled => 0 1
lead_time => Too many unique values (479)
arrival_date_year => 2024
arrival_date_month => July April September August October January December March June November February May
arrival_date_week_number => Too many unique values (52)
arrival_date_day_of_month => Too many unique values (31)
stays_in_weekend_nights => 0 1 2 4 3 6 13 8 5 7 12 9 16 18 19 10 14
stays_in_week_nights => Too many unique values (35)
adults => 2 1 3 4 40 26 50 27 55 0 20 6 5 10
children => 0.0 1.0 2.0 10.0 3.0 nan
babies => 0 1 2 10 9
meal => BB FB HB SC Undefined
country => Too many unique values (177)
market_segment => Direct Corporate Online TA Offline TA/TO Complementary Groups Undefined Aviation
distribution_channel => Direct Corporate TA/TO Undefined GDS
is_repeated_guest => 0 1
previous_cancellations => 0 1 2 3 26 25 14 4 24 19 5 21 6 13 11
previous_bookings_not_canceled => Too many unique values (73)
reserved_room_type => C A D E G F H L P B
assigned_room_type => C A D E G F I B H P L K
booking_changes => Too many unique values (21)
deposit_type => No Deposit Refundable Non Refund
agent => Too many unique values (333)
company => Too many unique values (352)
days_in_waiting_list => Too many unique values (128)
customer_type => Transient Contract Transient-Party Group
adr => Too many unique values (8879)
required_car_parking_spaces => 0 1 2 8 3
total_of_special_requests => 0 1 3 2 4 5
reservation_status => Check-Out Canceled No-Show
reservation_status_date => Too many unique values (34552)
city => Chandigarh Mumbai Delhi Kolkata Lucknow Indore Ahmedabad Pune Chennai Bhopal Hyderabad Kochi Bangalore Jaipur Goa

In [5]:
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
print("Missing Values Analysis:")
print(missing_values)

Missing Values Analysis:
children         4
country        488
agent        16340
company     112593
dtype: int64

# Drop

In [6]:
# Company => too many missing values (94.3%) and ID
# Reservation status => This column is related to the target value
# Agent => Id => It does not have predictive power
# reservation_status_date => it is not time format
# Arrival date year => 1 unique value (2024)

drop_cols=["company", "reservation_status", "agent", "reservation_status_date", "arrival_date_year"]

df.drop(columns=drop_cols, inplace=True)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_month              119390 non-null  str
 4   arrival_date_week_number        119390 non-null  int64
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119386 non-null  float64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  str
 12  country                         118902 non-null  str
 13  market_segment                  119390 non-null  str
 14  distribution_channel            119390 non-null  str
 15  is_repeated_guest               119390 non-null  int64
 16  previous_cancellations          119390 non-null  int64
 17  previous_bookings_not_canceled  119390 non-null  int64
 18  reserved_room_type              119390 non-null  str
 19  assigned_room_type              119390 non-null  str
 20  booking_changes                 119390 non-null  int64
 21  deposit_type                    119390 non-null  str
 22  days_in_waiting_list            119390 non-null  int64
 23  customer_type                   119390 non-null  str
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  city                            119390 non-null  str
dtypes: float64(2), int64(15), str(11)
memory usage: 25.5 MB

# Meal

In [8]:
df["meal"].unique()

<StringArray>
['BB', 'FB', 'HB', 'SC', 'Undefined']
Length: 5, dtype: str

In [9]:
df[df["meal"] == "Undefined"]

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,city
3106,Resort Hotel - Bhopal,0,105,June,25,21,2,4,2,0.0,...,A,A,0,No Deposit,65,Transient-Party,69.00,0,0,Bhopal
3107,Resort Hotel - Kolkata,0,105,April,16,18,2,4,2,0.0,...,A,A,0,No Deposit,65,Transient-Party,69.00,0,0,Kolkata
3108,Resort Hotel - Ahmedabad,0,105,November,45,4,2,4,2,0.0,...,A,A,0,No Deposit,65,Transient-Party,69.00,0,0,Ahmedabad
3110,Resort Hotel - Ahmedabad,0,62,May,19,7,2,4,2,0.0,...,A,A,0,No Deposit,0,Transient-Party,69.00,0,0,Ahmedabad
3111,Resort Hotel - Mumbai,0,105,May,20,13,2,4,2,0.0,...,A,A,0,No Deposit,65,Transient-Party,69.00,0,0,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39870,Resort Hotel - Mumbai,0,81,October,41,7,2,2,2,2.0,...,C,C,0,No Deposit,0,Transient,351.00,1,2,Mumbai
39874,Resort Hotel - Lucknow,0,191,March,10,5,2,5,2,1.0,...,A,I,1,No Deposit,0,Transient,169.98,1,2,Lucknow
39875,Resort Hotel - Bhopal,0,29,July,28,12,0,1,2,1.0,...,A,A,1,No Deposit,0,Group,204.00,1,2,Bhopal
39906,Resort Hotel - Chandigarh,0,8,June,25,18,0,2,2,0.0,...,D,D,1,No Deposit,0,Transient,266.06,1,0,Chandigarh
39962,Resort Hotel - Pune,0,2,May,20,15,0,3,2,0.0,...,A,D,2,No Deposit,0,Transient,245.33,0,2,Pune

In [10]:
df.groupby('meal')['is_canceled'].mean()

meal
BB           0.373849
FB           0.598997
HB           0.344603
SC           0.372394
Undefined    0.244654
Name: is_canceled, dtype: float64

In [11]:
df['meal'] = df['meal'].replace('Undefined', 'no_meal_type')

In [12]:
df["meal"].unique()

<StringArray>
['BB', 'FB', 'HB', 'SC', 'no_meal_type']
Length: 5, dtype: str

# Children

In [13]:
# 4 missing values
df = df.dropna(subset=["children"])

# Adults

In [14]:
df["adults"].value_counts().sort_index()

adults
0       403
1     23027
2     89677
3      6201
4        62
5         2
6         1
10        1
20        2
26        5
27        2
40        1
50        1
55        1
Name: count, dtype: int64

| Value Range | Explanation |
|---|---|
| 0–4 | 403, 23027, 89677, 6201, 62 — all of these are **realistic and occur in relatively large quantities**. |
| 5–6 | 2, 1 — rare, but still possible values (e.g., a large family). |
| 10, 20, 26, 27, 40, 50, 55 | **Very large values** — these may be suspicious or incorrectly entered. |

In [15]:
df[df["adults"] > 5]

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,city
1539,Resort Hotel - Chennai,1,304,October,42,20,0,3,40,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Chennai
1587,Resort Hotel - Indore,1,333,March,12,20,2,5,26,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Indore
1643,Resort Hotel - Chandigarh,1,336,September,38,21,1,2,50,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Chandigarh
1752,Resort Hotel - Kochi,1,340,December,50,15,2,5,26,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Kochi
1884,Resort Hotel - Kolkata,1,347,October,40,6,2,5,26,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Kolkata
1917,Resort Hotel - Bangalore,1,349,March,11,11,1,3,27,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Bangalore
1962,Resort Hotel - Goa,1,352,January,1,4,1,3,27,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Goa
2003,Resort Hotel - Delhi,1,354,April,15,12,2,5,26,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Delhi
2164,Resort Hotel - Hyderabad,1,361,April,15,8,2,5,26,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Hyderabad
2173,Resort Hotel - Goa,1,338,November,46,16,2,0,55,0.0,...,A,A,0,No Deposit,0,Group,0.0,0,0,Goa
2228,Resort Hotel - Ahmedabad,1,328,March,10,5,2,5,20,0.0,...,D,D,1,No Deposit,0,Group,0.0,0,0,Ahmedabad
2229,Resort Hotel - Chennai,1,328,February,8,22,2,5,6,0.0,...,E,E,0,No Deposit,0,Group,0.0,0,0,Chennai
2417,Resort Hotel - Goa,1,334,July,28,10,2,5,10,0.0,...,E,E,0,No Deposit,0,Group,0.0,0,0,Goa
2418,Resort Hotel - Bangalore,1,334,May,20,19,2,5,20,0.0,...,D,D,0,No Deposit,0,Group,0.0,0,0,Bangalore

In [16]:
df = df[df["adults"] <= 5]

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 119372 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119372 non-null  str
 1   is_canceled                     119372 non-null  int64
 2   lead_time                       119372 non-null  int64
 3   arrival_date_month              119372 non-null  str
 4   arrival_date_week_number        119372 non-null  int64
 5   arrival_date_day_of_month       119372 non-null  int64
 6   stays_in_weekend_nights         119372 non-null  int64
 7   stays_in_week_nights            119372 non-null  int64
 8   adults                          119372 non-null  int64
 9   children                        119372 non-null  float64
 10  babies                          119372 non-null  int64
 11  meal                            119372 non-null  str
 12  country                         118884 non-null  str
 13  market_segment                  119372 non-null  str
 14  distribution_channel            119372 non-null  str
 15  is_repeated_guest               119372 non-null  int64
 16  previous_cancellations          119372 non-null  int64
 17  previous_bookings_not_canceled  119372 non-null  int64
 18  reserved_room_type              119372 non-null  str
 19  assigned_room_type              119372 non-null  str
 20  booking_changes                 119372 non-null  int64
 21  deposit_type                    119372 non-null  str
 22  days_in_waiting_list            119372 non-null  int64
 23  customer_type                   119372 non-null  str
 24  adr                             119372 non-null  float64
 25  required_car_parking_spaces     119372 non-null  int64
 26  total_of_special_requests       119372 non-null  int64
 27  city                            119372 non-null  str
dtypes: float64(2), int64(15), str(11)
memory usage: 26.4 MB

# Children and babies

In [18]:
# If `adults = 0` while `children` or `babies` is greater than 0, this should be considered an invalid or illogical case, because children or babies cannot normally make a hotel reservation without an adult (parent or guardian).

In [19]:
df.loc[(df["adults"] == 0) & ((df["children"] > 0) | (df["babies"] > 0)), ["adults", "children", "babies", "is_canceled"]]

        adults  children  babies  is_canceled
40984        0       3.0       0            0
41048        0       2.0       0            0
41446        0       2.0       0            0
41952        0       2.0       0            0
45158        0       2.0       0            1
...        ...       ...     ...          ...
117204       0       2.0       0            0
117274       0       2.0       0            0
117303       0       2.0       0            0
117453       0       2.0       0            0
118200       0       3.0       0            0

[223 rows x 4 columns]

In [20]:
df.loc[(df["adults"] == 0) & (df["children"] == 0) & (df["babies"] == 0), ["adults", "children", "babies", "is_canceled"]]

        adults  children  babies  is_canceled
2224         0       0.0       0            0
2409         0       0.0       0            0
3181         0       0.0       0            0
3684         0       0.0       0            0
3708         0       0.0       0            0
...        ...       ...     ...          ...
115029       0       0.0       0            0
115091       0       0.0       0            0
116251       0       0.0       0            0
116534       0       0.0       0            0
117087       0       0.0       0            0

[180 rows x 4 columns]

In [21]:
df = df[~((df["adults"] == 0) & ((df["children"] > 0) | (df["babies"] > 0)))]

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 119149 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119149 non-null  str
 1   is_canceled                     119149 non-null  int64
 2   lead_time                       119149 non-null  int64
 3   arrival_date_month              119149 non-null  str
 4   arrival_date_week_number        119149 non-null  int64
 5   arrival_date_day_of_month       119149 non-null  int64
 6   stays_in_weekend_nights         119149 non-null  int64
 7   stays_in_week_nights            119149 non-null  int64
 8   adults                          119149 non-null  int64
 9   children                        119149 non-null  float64
 10  babies                          119149 non-null  int64
 11  meal                            119149 non-null  str
 12  country                         118661 non-null  str
 13  market_segment                  119149 non-null  str
 14  distribution_channel            119149 non-null  str
 15  is_repeated_guest               119149 non-null  int64
 16  previous_cancellations          119149 non-null  int64
 17  previous_bookings_not_canceled  119149 non-null  int64
 18  reserved_room_type              119149 non-null  str
 19  assigned_room_type              119149 non-null  str
 20  booking_changes                 119149 non-null  int64
 21  deposit_type                    119149 non-null  str
 22  days_in_waiting_list            119149 non-null  int64
 23  customer_type                   119149 non-null  str
 24  adr                             119149 non-null  float64
 25  required_car_parking_spaces     119149 non-null  int64
 26  total_of_special_requests       119149 non-null  int64
 27  city                            119149 non-null  str
dtypes: float64(2), int64(15), str(11)
memory usage: 26.4 MB

# Country

In [23]:
df["country"].unique()

<StringArray>
['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA',   nan, 'ROU', 'NOR', 'OMN',
 ...
 'ATA', 'GTM', 'ASM', 'MRT', 'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO']
Length: 178, dtype: str

In [24]:
df[df["country"].isna()]["is_canceled"].mean()

np.float64(0.13729508196721313)

In [25]:
df["is_canceled"].mean()

np.float64(0.3703094444770833)

In [26]:
df["country"] = df["country"].fillna("Unknown")

In [27]:
# The missing values in the country column were replaced with "Unknown" because the missingness itself appears to have a relationship with the target variable. The cancellation rate for records with a missing country value is 13.73%, compared to 37.03% for the overall dataset. Therefore, instead of removing these rows, the missing values were treated as a separate category, "Unknown", to preserve potentially useful information for the model.

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 119149 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119149 non-null  str
 1   is_canceled                     119149 non-null  int64
 2   lead_time                       119149 non-null  int64
 3   arrival_date_month              119149 non-null  str
 4   arrival_date_week_number        119149 non-null  int64
 5   arrival_date_day_of_month       119149 non-null  int64
 6   stays_in_weekend_nights         119149 non-null  int64
 7   stays_in_week_nights            119149 non-null  int64
 8   adults                          119149 non-null  int64
 9   children                        119149 non-null  float64
 10  babies                          119149 non-null  int64
 11  meal                            119149 non-null  str
 12  country                         119149 non-null  str
 13  market_segment                  119149 non-null  str
 14  distribution_channel            119149 non-null  str
 15  is_repeated_guest               119149 non-null  int64
 16  previous_cancellations          119149 non-null  int64
 17  previous_bookings_not_canceled  119149 non-null  int64
 18  reserved_room_type              119149 non-null  str
 19  assigned_room_type              119149 non-null  str
 20  booking_changes                 119149 non-null  int64
 21  deposit_type                    119149 non-null  str
 22  days_in_waiting_list            119149 non-null  int64
 23  customer_type                   119149 non-null  str
 24  adr                             119149 non-null  float64
 25  required_car_parking_spaces     119149 non-null  int64
 26  total_of_special_requests       119149 non-null  int64
 27  city                            119149 non-null  str
dtypes: float64(2), int64(15), str(11)
memory usage: 26.4 MB

# Distribution channel

In [29]:
df.groupby("distribution_channel")["is_canceled"].mean().sort_values(ascending=False)

distribution_channel
TA/TO        0.410248
Corporate    0.220758
GDS          0.191710
Direct       0.173937
Undefined    0.000000
Name: is_canceled, dtype: float64

In [30]:
df["distribution_channel"].value_counts()

distribution_channel
TA/TO        97675
Direct       14603
Corporate     6677
GDS            193
Undefined        1
Name: count, dtype: int64

In [31]:
df = df[df["distribution_channel"] != "Undefined"]

# Data leakage

In [32]:
target = "is_canceled"
x=df.drop(columns=[target])
y=df[target]

In [33]:
x.info()

<class 'pandas.DataFrame'>
Index: 119148 entries, 0 to 119389
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119148 non-null  str
 1   lead_time                       119148 non-null  int64
 2   arrival_date_month              119148 non-null  str
 3   arrival_date_week_number        119148 non-null  int64
 4   arrival_date_day_of_month       119148 non-null  int64
 5   stays_in_weekend_nights         119148 non-null  int64
 6   stays_in_week_nights            119148 non-null  int64
 7   adults                          119148 non-null  int64
 8   children                        119148 non-null  float64
 9   babies                          119148 non-null  int64
 10  meal                            119148 non-null  str
 11  country                         119148 non-null  str
 12  market_segment                  119148 non-null  str
 13  distribution_channel            119148 non-null  str
 14  is_repeated_guest               119148 non-null  int64
 15  previous_cancellations          119148 non-null  int64
 16  previous_bookings_not_canceled  119148 non-null  int64
 17  reserved_room_type              119148 non-null  str
 18  assigned_room_type              119148 non-null  str
 19  booking_changes                 119148 non-null  int64
 20  deposit_type                    119148 non-null  str
 21  days_in_waiting_list            119148 non-null  int64
 22  customer_type                   119148 non-null  str
 23  adr                             119148 non-null  float64
 24  required_car_parking_spaces     119148 non-null  int64
 25  total_of_special_requests       119148 non-null  int64
 26  city                            119148 non-null  str
dtypes: float64(2), int64(14), str(11)
memory usage: 25.5 MB

In [34]:
y.info()

<class 'pandas.Series'>
Index: 119148 entries, 0 to 119389
Series name: is_canceled
Non-Null Count   Dtype
--------------   -----
119148 non-null  int64
dtypes: int64(1)
memory usage: 1.8 MB

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [36]:
x_train.shape

(95318, 27)

In [37]:
x_test.shape

(23830, 27)

In [38]:
y_train.shape

(95318,)

In [39]:
y_test.shape

(23830,)

# Feature Engineering

In [40]:
x_train.info()

<class 'pandas.DataFrame'>
Index: 95318 entries, 68612 to 15810
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           95318 non-null  str
 1   lead_time                       95318 non-null  int64
 2   arrival_date_month              95318 non-null  str
 3   arrival_date_week_number        95318 non-null  int64
 4   arrival_date_day_of_month       95318 non-null  int64
 5   stays_in_weekend_nights         95318 non-null  int64
 6   stays_in_week_nights            95318 non-null  int64
 7   adults                          95318 non-null  int64
 8   children                        95318 non-null  float64
 9   babies                          95318 non-null  int64
 10  meal                            95318 non-null  str
 11  country                         95318 non-null  str
 12  market_segment                  95318 non-null  str
 13  distribution_channel            95318 non-null  str
 14  is_repeated_guest               95318 non-null  int64
 15  previous_cancellations          95318 non-null  int64
 16  previous_bookings_not_canceled  95318 non-null  int64
 17  reserved_room_type              95318 non-null  str
 18  assigned_room_type              95318 non-null  str
 19  booking_changes                 95318 non-null  int64
 20  deposit_type                    95318 non-null  str
 21  days_in_waiting_list            95318 non-null  int64
 22  customer_type                   95318 non-null  str
 23  adr                             95318 non-null  float64
 24  required_car_parking_spaces     95318 non-null  int64
 25  total_of_special_requests       95318 non-null  int64
 26  city                            95318 non-null  str
dtypes: float64(2), int64(14), str(11)
memory usage: 20.4 MB

In [41]:
x_train["lead_time"].describe()

count    95318.000000
mean       103.856344
std        106.709603
min          0.000000
25%         18.000000
50%         69.000000
75%        160.000000
max        737.000000
Name: lead_time, dtype: float64

In [42]:
x_train["arrival_date_month"].head()

68612          May
115688    February
51003     December
66081      October
40494      October
Name: arrival_date_month, dtype: str

In [43]:
x_train["arrival_date_week_number"].describe()

count    95318.000000
mean        26.363499
std         15.023635
min          1.000000
25%         13.000000
50%         26.000000
75%         39.000000
max         52.000000
Name: arrival_date_week_number, dtype: float64

In [44]:
x_train["arrival_date_day_of_month"].describe()

count    95318.000000
mean        15.728844
std          8.796291
min          1.000000
25%          8.000000
50%         16.000000
75%         23.000000
max         31.000000
Name: arrival_date_day_of_month, dtype: float64

# Season feature

In [45]:
def get_season(month):
    season_dict = {
        'December': 'Winter', 'January': 'Winter', 'February': 'Winter',
        'March': 'Spring', 'April': 'Spring', 'May': 'Spring',
        'June': 'Summer', 'July': 'Summer', 'August': 'Summer',
        'September': 'Autumn', 'October': 'Autumn', 'November': 'Autumn'
    }
    return season_dict.get(month, 'Unknown')

x_train['fe_season'] = x_train['arrival_date_month'].apply(get_season)
x_test['fe_season'] = x_test['arrival_date_month'].apply(get_season)

In [46]:
x_train['fe_season'].describe()

count      95318
unique         4
top       Spring
freq       24145
Name: fe_season, dtype: object

In [47]:
y_train.groupby(x_train["arrival_date_month"]).mean().sort_values(ascending=False)

arrival_date_month
November     0.379203
January      0.377588
October      0.371793
June         0.370124
May          0.369895
April        0.369347
August       0.368703
September    0.368414
July         0.367579
February     0.367368
December     0.366950
March        0.366247
Name: is_canceled, dtype: float64

In [48]:
y_train.groupby(x_train["fe_season"]).mean().sort_values(ascending=False)

fe_season
Autumn    0.373095
Winter    0.370759
Summer    0.368782
Spring    0.368482
Name: is_canceled, dtype: float64

In [49]:
x_train["stays_in_weekend_nights"].unique()

array([ 0,  1,  2,  9,  6,  4,  3,  5,  8,  7, 12, 14, 10, 16, 18, 19, 13])

In [50]:
x_train["stays_in_week_nights"].unique()

array([ 2,  4,  3,  1,  5, 21,  0,  6, 13, 10,  8,  7,  9, 12, 20, 19, 11,
       15, 24, 22, 16, 30, 14, 34, 18, 17, 26, 40, 35, 42, 25, 50, 33, 32])

# total nights feature

In [51]:
x_train["fe_total_nights"] = x_train["stays_in_weekend_nights"] + x_train["stays_in_week_nights"]
x_test["fe_total_nights"] = x_test["stays_in_weekend_nights"] + x_test["stays_in_week_nights"]

In [52]:
y_train.groupby(x_train["fe_total_nights"]).mean().sort_values(ascending=False)

fe_total_nights
33    1.000000
26    1.000000
20    0.916667
19    0.833333
30    0.818182
27    0.800000
24    0.800000
23    0.800000
18    0.793103
29    0.750000
25    0.666667
16    0.542857
15    0.508475
56    0.500000
21    0.482143
12    0.445087
2     0.442054
3     0.419525
28    0.400000
6     0.398900
9     0.378049
8     0.370933
4     0.363004
13    0.356522
7     0.343809
5     0.339561
17    0.307692
10    0.302732
11    0.299674
14    0.282548
22    0.272727
42    0.250000
1     0.249851
0     0.053819
38    0.000000
35    0.000000
43    0.000000
45    0.000000
46    0.000000
48    0.000000
49    0.000000
34    0.000000
60    0.000000
69    0.000000
Name: is_canceled, dtype: float64

# Is weekend stay

In [53]:
x_train["fe_is_weekend_stay"] = (x_train["stays_in_weekend_nights"] > 0).astype(int)
x_test["fe_is_weekend_stay"] = (x_test["stays_in_weekend_nights"] > 0).astype(int)

# Weekend ration

In [54]:
x_train["fe_weekend_ratio"] = x_train["stays_in_weekend_nights"] / (x_train["fe_total_nights"] + 1)  # +1 is added to avoid division by zero.
x_test["fe_weekend_ratio"] = x_test["stays_in_weekend_nights"] / (x_test["fe_total_nights"] + 1)

# total guests

In [55]:
x_train["fe_total_guests"] = x_train["adults"] + x_train["children"] + x_train["babies"]
x_test["fe_total_guests"] = x_test["adults"] + x_test["children"] + x_test["babies"]

In [56]:
y_train.groupby(x_train["fe_total_guests"]).mean().sort_values(ascending=False)

fe_total_guests
12.0    1.000000
4.0     0.417734
2.0     0.396948
3.0     0.321157
1.0     0.290674
5.0     0.262136
0.0     0.142857
Name: is_canceled, dtype: float64

# Room type mismatch

In [57]:
x_train["fe_room_type_mismatch"] = (x_train["reserved_room_type"] != x_train["assigned_room_type"]).astype(int)
x_test["fe_room_type_mismatch"] = (x_test["reserved_room_type"] != x_test["assigned_room_type"]).astype(int)

# Has previous cancellation?

In [58]:
x_train["fe_has_previous_cancellations"] = (x_train["previous_cancellations"] > 0).astype(int)
x_test["fe_has_previous_cancellations"] = (x_test["previous_cancellations"] > 0).astype(int)

# Has booking changes?

In [59]:
x_train["previous_cancellations"].value_counts()

previous_cancellations
0     90130
1      4848
2        89
3        51
24       39
11       29
4        26
25       21
26       18
5        17
6        15
19       13
13       11
14       10
21        1
Name: count, dtype: int64

In [60]:
x_train["fe_has_booking_changes"] = (x_train["booking_changes"] > 0).astype(int)
x_test["fe_has_booking_changes"] = (x_test["booking_changes"] > 0).astype(int)

# Deposit

In [61]:
x_train["deposit_type"].unique()

<StringArray>
['Non Refund', 'No Deposit', 'Refundable']
Length: 3, dtype: str

In [62]:
x_train["fe_has_deposit"] = (x_train["deposit_type"] != "No Deposit").astype(int)
x_test["fe_has_deposit"] = (x_test["deposit_type"] != "No Deposit").astype(int)

# Car parking

In [63]:
x_train["required_car_parking_spaces"].unique()

array([0, 2, 1, 8, 3])

In [64]:
x_train["fe_has_parking_request"] = (x_train["required_car_parking_spaces"] > 0).astype(int)
x_test["fe_has_parking_request"] = (x_test["required_car_parking_spaces"] > 0).astype(int)

# Special requests

In [65]:
x_train["total_of_special_requests"].unique()

array([0, 1, 2, 3, 4, 5])

In [66]:
x_train["fe_has_special_request"] = (x_train["total_of_special_requests"] > 0).astype(int)
x_test["fe_has_special_request"] = (x_test["total_of_special_requests"] > 0).astype(int)

In [67]:
x_train.info()

<class 'pandas.DataFrame'>
Index: 95318 entries, 68612 to 15810
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           95318 non-null  str
 1   lead_time                       95318 non-null  int64
 2   arrival_date_month              95318 non-null  str
 3   arrival_date_week_number        95318 non-null  int64
 4   arrival_date_day_of_month       95318 non-null  int64
 5   stays_in_weekend_nights         95318 non-null  int64
 6   stays_in_week_nights            95318 non-null  int64
 7   adults                          95318 non-null  int64
 8   children                        95318 non-null  float64
 9   babies                          95318 non-null  int64
 10  meal                            95318 non-null  str
 11  country                         95318 non-null  str
 12  market_segment                  95318 non-null  str
 13  distribution_channel            95318 non-null  str
 14  is_repeated_guest               95318 non-null  int64
 15  previous_cancellations          95318 non-null  int64
 16  previous_bookings_not_canceled  95318 non-null  int64
 17  reserved_room_type              95318 non-null  str
 18  assigned_room_type              95318 non-null  str
 19  booking_changes                 95318 non-null  int64
 20  deposit_type                    95318 non-null  str
 21  days_in_waiting_list            95318 non-null  int64
 22  customer_type                   95318 non-null  str
 23  adr                             95318 non-null  float64
 24  required_car_parking_spaces     95318 non-null  int64
 25  total_of_special_requests       95318 non-null  int64
 26  city                            95318 non-null  str
 27  fe_season                       95318 non-null  str
 28  fe_total_nights                 95318 non-null  int64
 29  fe_is_weekend_stay              95318 non-null  int64
 30  fe_weekend_ratio                95318 non-null  float64
 31  fe_total_guests                 95318 non-null  float64
 32  fe_room_type_mismatch           95318 non-null  int64
 33  fe_has_previous_cancellations   95318 non-null  int64
 34  fe_has_booking_changes          95318 non-null  int64
 35  fe_has_deposit                  95318 non-null  int64
 36  fe_has_parking_request          95318 non-null  int64
 37  fe_has_special_request          95318 non-null  int64
dtypes: float64(4), int64(22), str(12)
memory usage: 28.4 MB

In [68]:
x_test.info()

<class 'pandas.DataFrame'>
Index: 23830 entries, 74164 to 113178
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           23830 non-null  str
 1   lead_time                       23830 non-null  int64
 2   arrival_date_month              23830 non-null  str
 3   arrival_date_week_number        23830 non-null  int64
 4   arrival_date_day_of_month       23830 non-null  int64
 5   stays_in_weekend_nights         23830 non-null  int64
 6   stays_in_week_nights            23830 non-null  int64
 7   adults                          23830 non-null  int64
 8   children                        23830 non-null  float64
 9   babies                          23830 non-null  int64
 10  meal                            23830 non-null  str
 11  country                         23830 non-null  str
 12  market_segment                  23830 non-null  str
 13  distribution_channel            23830 non-null  str
 14  is_repeated_guest               23830 non-null  int64
 15  previous_cancellations          23830 non-null  int64
 16  previous_bookings_not_canceled  23830 non-null  int64
 17  reserved_room_type              23830 non-null  str
 18  assigned_room_type              23830 non-null  str
 19  booking_changes                 23830 non-null  int64
 20  deposit_type                    23830 non-null  str
 21  days_in_waiting_list            23830 non-null  int64
 22  customer_type                   23830 non-null  str
 23  adr                             23830 non-null  float64
 24  required_car_parking_spaces     23830 non-null  int64
 25  total_of_special_requests       23830 non-null  int64
 26  city                            23830 non-null  str
 27  fe_season                       23830 non-null  str
 28  fe_total_nights                 23830 non-null  int64
 29  fe_is_weekend_stay              23830 non-null  int64
 30  fe_weekend_ratio                23830 non-null  float64
 31  fe_total_guests                 23830 non-null  float64
 32  fe_room_type_mismatch           23830 non-null  int64
 33  fe_has_previous_cancellations   23830 non-null  int64
 34  fe_has_booking_changes          23830 non-null  int64
 35  fe_has_deposit                  23830 non-null  int64
 36  fe_has_parking_request          23830 non-null  int64
 37  fe_has_special_request          23830 non-null  int64
dtypes: float64(4), int64(22), str(12)
memory usage: 7.1 MB

In [69]:
x_train.dtypes

hotel                                 str
lead_time                           int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
city                                  str
fe_season                             str
fe_total_nights                     int64
fe_is_weekend_stay                  int64
fe_weekend_ratio                  float64
fe_total_guests                   float64
fe_room_type_mismatch               int64
fe_has_previous_cancellations       int64
fe_has_booking_changes              int64
fe_has_deposit                      int64
fe_has_parking_request              int64
fe_has_special_request              int64
dtype: object

# Skewness

In [70]:
import numpy as np

numeric_features = x_train.select_dtypes(
    include="number"
).columns

continuous_features = [
    col for col in numeric_features
    if x_train[col].nunique() > 2
    and np.issubdtype(x_train[col].dtype, np.number)
]

In [71]:
skewness = x_train[continuous_features].skew()

skewed_features = skewness[
    abs(skewness) >= 0.8
].sort_values(ascending=False)

print(skewed_features)

previous_cancellations            24.618269
previous_bookings_not_canceled    23.372040
adr                               12.456198
days_in_waiting_list              11.936954
babies                            11.692658
booking_changes                    6.130934
required_car_parking_spaces        4.303223
children                           4.224430
fe_total_nights                    3.377112
stays_in_week_nights               2.918669
stays_in_weekend_nights            1.413753
lead_time                          1.348051
total_of_special_requests          1.341948
fe_total_guests                    0.846098
dtype: float64

In [72]:
X_train_transformed = x_train.copy()
X_test_transformed = x_test.copy()

for col in skewed_features.index:

    if (X_train_transformed[col] >= 0).all():
        X_train_transformed[col] = np.log1p(
            X_train_transformed[col]
        )
        
        X_test_transformed[col] = np.log1p(
            X_test_transformed[col]
        )

In [73]:
skewness_after = X_train_transformed[
    continuous_features
].skew()

comparison = pd.DataFrame({
    "Before": skewness,
    "After": skewness_after
})

print(comparison.sort_values("Before", ascending=False))

                                   Before      After
previous_cancellations          24.618269   7.309206
previous_bookings_not_canceled  23.372040   8.121393
adr                             12.456198  12.456198
days_in_waiting_list            11.936954   5.748615
babies                          11.692658  11.390871
booking_changes                  6.130934   2.586217
required_car_parking_spaces      4.303223   3.689460
children                         4.224430   3.717653
fe_total_nights                  3.377112   0.345866
stays_in_week_nights             2.918669  -0.117018
stays_in_weekend_nights          1.413753   0.195693
lead_time                        1.348051  -0.872975
total_of_special_requests        1.341948   0.746695
fe_total_guests                  0.846098  -0.241108
fe_weekend_ratio                 0.516406   0.516406
arrival_date_week_number         0.005121   0.005121
arrival_date_day_of_month       -0.000371  -0.000371
adults                          -0.401770  -0.401770

# Encoding

In [74]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler 

def encode_train(df):
    df = df.copy()
    encoders = {}

    for col in df.select_dtypes(exclude=np.number).columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        encoders[col] = le
    return df, encoders

def encode_test(df, encoders, train_columns):
    df = df.copy()

    # Label encoding
    for col, le in encoders.items():
        df[col] = df[col].astype(str)
        df[col] = df[col].apply(lambda x: le.transform([x])[0] if x in le.classes_ else -1)

    # Align columns
    df = df.reindex(columns=train_columns, fill_value=0)

    return df
    
def scale_train(df):
    df = df.copy()
    scalers = {}

    for col in df.select_dtypes(include=np.number).columns:
        scaler = StandardScaler()
        df[col] = scaler.fit_transform(df[[col]])
        scalers[col] = scaler

    return df, scalers

def scale_test(df, scalers):
    df = df.copy()

    for col in df.columns:
        if col in scalers:
            df[col] = scalers[col].transform(df[[col]])

    return df

In [75]:
# Encoding
x_train_encoded, encoders = encode_train(X_train_transformed)
x_test_encoded = encode_test(X_test_transformed, encoders, X_train_transformed.columns)

In [76]:
x_train_encoded

,hotel,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,fe_total_nights,fe_is_weekend_stay,fe_weekend_ratio,fe_total_guests,fe_room_type_mismatch,fe_has_previous_cancellations,fe_has_booking_changes,fe_has_deposit,fe_has_parking_request,fe_has_special_request
68612,2,4.663439,8,19,11,0.000000,1.098612,1,0.000000,0.0,...,1.098612,0,0.000000,0.693147,0,0,0,1,0,0
115688,8,5.170484,3,8,21,0.693147,1.609438,2,0.000000,0.0,...,1.791759,1,0.166667,1.098612,0,0,0,0,0,0
51003,7,4.521789,2,49,7,0.693147,1.098612,2,0.000000,0.0,...,1.386294,1,0.250000,1.098612,0,0,0,0,0,0
66081,2,4.836282,10,41,9,1.098612,1.386294,2,0.693147,0.0,...,1.791759,1,0.333333,1.386294,0,0,0,0,0,0
40494,10,3.258097,10,41,8,0.693147,0.693147,1,0.000000,0.0,...,1.098612,1,0.333333,0.693147,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76954,12,5.837730,7,11,15,1.098612,1.609438,2,0.000000,0.0,...,1.945910,1,0.285714,1.098612,0,1,0,1,0,0
110494,5,3.663562,11,38,17,0.693147,1.386294,2,0.000000,0.0,...,1.609438,1,0.200000,1.098612,0,0,1,0,0,1
103905,1,1.945910,10,42,15,0.693147,1.098612,2,0.000000,0.0,...,1.386294,1,0.250000,1.098612,0,0,0,0,0,0
860,26,4.875197,6,23,5,1.098612,1.791759,2,0.000000,0.0,...,2.079442,1,0.250000,1.098612,0,0,0,0,0,1
15810,17,1.386294,9,46,13,0.693147,1.386294,2,1.098612,0.0,...,1.609438,1,0.200000,1.609438,0,0,1,0,0,1

In [77]:
x_test_encoded

,hotel,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,fe_total_nights,fe_is_weekend_stay,fe_weekend_ratio,fe_total_guests,fe_room_type_mismatch,fe_has_previous_cancellations,fe_has_booking_changes,fe_has_deposit,fe_has_parking_request,fe_has_special_request
74164,14,5.857933,9,45,8,0.000000,1.098612,2,0.000000,0.0,...,1.098612,0,0.000000,1.098612,0,1,0,1,0,0
83833,1,0.000000,1,35,26,0.000000,1.098612,2,0.000000,0.0,...,1.098612,0,0.000000,1.098612,0,0,0,0,0,0
12772,26,5.811141,9,48,29,1.098612,1.609438,2,0.000000,0.0,...,1.945910,1,0.285714,1.098612,0,0,0,0,0,1
114293,3,6.107023,5,28,14,1.098612,0.693147,2,0.000000,0.0,...,1.386294,1,0.500000,1.098612,0,0,0,0,0,1
64762,4,6.423247,0,15,11,0.000000,0.693147,1,0.000000,0.0,...,0.693147,0,0.000000,0.693147,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4134,16,5.241747,4,4,24,0.693147,1.791759,2,0.693147,0.0,...,1.945910,1,0.142857,1.386294,0,0,1,0,0,1
81358,4,2.484907,5,31,29,1.098612,1.098612,2,0.000000,0.0,...,1.609438,1,0.400000,1.098612,0,0,0,0,0,0
57851,2,5.198497,1,32,11,1.098612,0.693147,2,0.000000,0.0,...,1.386294,1,0.500000,1.098612,0,0,0,0,0,0
41262,11,0.000000,2,51,22,0.000000,1.098612,2,0.000000,0.0,...,1.098612,0,0.000000,1.098612,0,0,0,0,0,0
113178,2,5.176150,1,34,22,0.000000,1.386294,2,0.000000,0.0,...,1.386294,0,0.000000,1.098612,0,0,0,0,0,1

In [78]:
# Scaling
x_train_scaled, scalers = scale_train(df=x_train_encoded)
x_test_scaled = scale_test(df=x_test_encoded, scalers=scalers)

In [79]:
x_train_scaled.info()

<class 'pandas.DataFrame'>
Index: 95318 entries, 68612 to 15810
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           95318 non-null  float64
 1   lead_time                       95318 non-null  float64
 2   arrival_date_month              95318 non-null  float64
 3   arrival_date_week_number        95318 non-null  float64
 4   arrival_date_day_of_month       95318 non-null  float64
 5   stays_in_weekend_nights         95318 non-null  float64
 6   stays_in_week_nights            95318 non-null  float64
 7   adults                          95318 non-null  float64
 8   children                        95318 non-null  float64
 9   babies                          95318 non-null  float64
 10  meal                            95318 non-null  float64
 11  country                         95318 non-null  float64
 12  market_segment                  95318 non-null  float64
 13  distribution_channel            95318 non-null  float64
 14  is_repeated_guest               95318 non-null  float64
 15  previous_cancellations          95318 non-null  float64
 16  previous_bookings_not_canceled  95318 non-null  float64
 17  reserved_room_type              95318 non-null  float64
 18  assigned_room_type              95318 non-null  float64
 19  booking_changes                 95318 non-null  float64
 20  deposit_type                    95318 non-null  float64
 21  days_in_waiting_list            95318 non-null  float64
 22  customer_type                   95318 non-null  float64
 23  adr                             95318 non-null  float64
 24  required_car_parking_spaces     95318 non-null  float64
 25  total_of_special_requests       95318 non-null  float64
 26  city                            95318 non-null  float64
 27  fe_season                       95318 non-null  float64
 28  fe_total_nights                 95318 non-null  float64
 29  fe_is_weekend_stay              95318 non-null  float64
 30  fe_weekend_ratio                95318 non-null  float64
 31  fe_total_guests                 95318 non-null  float64
 32  fe_room_type_mismatch           95318 non-null  float64
 33  fe_has_previous_cancellations   95318 non-null  float64
 34  fe_has_booking_changes          95318 non-null  float64
 35  fe_has_deposit                  95318 non-null  float64
 36  fe_has_parking_request          95318 non-null  float64
 37  fe_has_special_request          95318 non-null  float64
dtypes: float64(38)
memory usage: 28.4 MB

In [80]:
x_test_scaled.info()

<class 'pandas.DataFrame'>
Index: 23830 entries, 74164 to 113178
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           23830 non-null  float64
 1   lead_time                       23830 non-null  float64
 2   arrival_date_month              23830 non-null  float64
 3   arrival_date_week_number        23830 non-null  float64
 4   arrival_date_day_of_month       23830 non-null  float64
 5   stays_in_weekend_nights         23830 non-null  float64
 6   stays_in_week_nights            23830 non-null  float64
 7   adults                          23830 non-null  float64
 8   children                        23830 non-null  float64
 9   babies                          23830 non-null  float64
 10  meal                            23830 non-null  float64
 11  country                         23830 non-null  float64
 12  market_segment                  23830 non-null  float64
 13  distribution_channel            23830 non-null  float64
 14  is_repeated_guest               23830 non-null  float64
 15  previous_cancellations          23830 non-null  float64
 16  previous_bookings_not_canceled  23830 non-null  float64
 17  reserved_room_type              23830 non-null  float64
 18  assigned_room_type              23830 non-null  float64
 19  booking_changes                 23830 non-null  float64
 20  deposit_type                    23830 non-null  float64
 21  days_in_waiting_list            23830 non-null  float64
 22  customer_type                   23830 non-null  float64
 23  adr                             23830 non-null  float64
 24  required_car_parking_spaces     23830 non-null  float64
 25  total_of_special_requests       23830 non-null  float64
 26  city                            23830 non-null  float64
 27  fe_season                       23830 non-null  float64
 28  fe_total_nights                 23830 non-null  float64
 29  fe_is_weekend_stay              23830 non-null  float64
 30  fe_weekend_ratio                23830 non-null  float64
 31  fe_total_guests                 23830 non-null  float64
 32  fe_room_type_mismatch           23830 non-null  float64
 33  fe_has_previous_cancellations   23830 non-null  float64
 34  fe_has_booking_changes          23830 non-null  float64
 35  fe_has_deposit                  23830 non-null  float64
 36  fe_has_parking_request          23830 non-null  float64
 37  fe_has_special_request          23830 non-null  float64
dtypes: float64(38)
memory usage: 7.1 MB

# Feature Selection

In [81]:
# Correlation
correlations = x_train_scaled.corrwith(y_train)
correlations

hotel                            -0.116384
lead_time                         0.320293
arrival_date_month                0.002046
arrival_date_week_number          0.000048
arrival_date_day_of_month        -0.003846
stays_in_weekend_nights          -0.003307
stays_in_week_nights              0.048510
adults                            0.062265
children                          0.003946
babies                           -0.034669
meal                             -0.015412
country                           0.264691
market_segment                    0.056954
distribution_channel              0.166530
is_repeated_guest                -0.084003
previous_cancellations            0.231118
previous_bookings_not_canceled   -0.098053
reserved_room_type               -0.060746
assigned_room_type               -0.174731
booking_changes                  -0.170554
deposit_type                      0.468359
days_in_waiting_list              0.091795
customer_type                    -0.066947
adr                               0.046266
required_car_parking_spaces      -0.196086
total_of_special_requests        -0.251375
city                              0.000725
fe_season                        -0.001559
fe_total_nights                   0.044579
fe_is_weekend_stay               -0.007397
fe_weekend_ratio                 -0.010287
fe_total_guests                   0.056370
fe_room_type_mismatch            -0.246455
fe_has_previous_cancellations     0.272855
fe_has_booking_changes           -0.185528
fe_has_deposit                    0.477865
fe_has_parking_request           -0.196432
fe_has_special_request           -0.262740
dtype: float64

In [82]:
import plotly.express as px

corr_matrix = x_train_scaled.corr()

fig = px.imshow(
    corr_matrix,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale='RdBu_r',
    title="Feature Correlation Matrix"
)

fig.show()

In [83]:
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

to_drop = [
    column
    for column in upper.columns
    if any(upper[column] > 0.80)
]
print("drop cols: ", to_drop)
# x_train_selected = x_train_scaled.drop(columns=to_drop)
# x_train_selected.info()

drop cols:  ['assigned_room_type', 'fe_total_nights', 'fe_is_weekend_stay', 'fe_weekend_ratio', 'fe_total_guests', 'fe_has_previous_cancellations', 'fe_has_booking_changes', 'fe_has_deposit', 'fe_has_parking_request', 'fe_has_special_request']

# Logistic Regression

In [81]:
import pandas as pd

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

In [82]:
selector = SelectFromModel(
    LogisticRegression(
        penalty="l1",
        solver="liblinear",
        C=1.0,
        max_iter=1000,
        random_state=42
    ),
    threshold="mean"
)

pipeline = Pipeline([
    ("selector", selector),

    ("sampler", SMOTE(
        random_state=42
    )),

    ("model", LogisticRegression(
        penalty="l1",
        solver="liblinear",
        C=1.0,
        max_iter=1000,
        random_state=42
    ))
])

In [83]:
pipeline

Pipeline(steps=[('selector',
                 SelectFromModel(estimator=LogisticRegression(max_iter=1000,
                                                              penalty='l1',
                                                              random_state=42,
                                                              solver='liblinear'),
                                 threshold='mean')),
                ('sampler', SMOTE(random_state=42)),
                ('model',
                 LogisticRegression(max_iter=1000, penalty='l1',
                                    random_state=42, solver='liblinear'))])

In [84]:
pipeline.fit(
    x_train_scaled,
    y_train
)

/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Pipeline(steps=[('selector',
                 SelectFromModel(estimator=LogisticRegression(max_iter=1000,
                                                              penalty='l1',
                                                              random_state=42,
                                                              solver='liblinear'),
                                 threshold='mean')),
                ('sampler', SMOTE(random_state=42)),
                ('model',
                 LogisticRegression(max_iter=1000, penalty='l1',
                                    random_state=42, solver='liblinear'))])

In [85]:
# Before Selector 
X_train_selected = pipeline.named_steps["selector"].transform(
    x_train_scaled
)

# After SMOTE
X_train_smote, y_train_smote = pipeline.named_steps["sampler"].fit_resample(
    X_train_selected,
    y_train
)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(pd.Series(y_train_smote).value_counts())

print("\nShape before SMOTE:")
print(X_train_selected.shape)

print("\nShape after SMOTE:")
print(X_train_smote.shape)

Before SMOTE:
is_canceled
0    60025
1    35293
Name: count, dtype: int64

After SMOTE:
is_canceled
1    60025
0    60025
Name: count, dtype: int64

Shape before SMOTE:
(95318, 11)

Shape after SMOTE:
(120050, 11)

In [86]:
selected_mask = pipeline.named_steps["selector"].get_support()
selected_features = x_train_scaled.columns[selected_mask]

print(f"Number of selected features: {len(selected_features)} / {x_train_scaled.shape[1]}")
print(selected_features.tolist())

Number of selected features: 11 / 38
['lead_time', 'country', 'market_segment', 'distribution_channel', 'deposit_type', 'required_car_parking_spaces', 'fe_room_type_mismatch', 'fe_has_previous_cancellations', 'fe_has_booking_changes', 'fe_has_deposit', 'fe_has_parking_request']

In [87]:
dropped_features = x_train_scaled.columns[~selected_mask]
print(f"Dropped features: {dropped_features.tolist()}")

Dropped features: ['hotel', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'days_in_waiting_list', 'customer_type', 'adr', 'total_of_special_requests', 'city', 'fe_season', 'fe_total_nights', 'fe_is_weekend_stay', 'fe_weekend_ratio', 'fe_total_guests', 'fe_has_special_request']

In [88]:
coefs = pipeline.named_steps["selector"].estimator_.coef_[0]
feature_importance = pd.Series(coefs, index=x_train_scaled.columns).sort_values(key=abs, ascending=False)
print(feature_importance)

fe_has_deposit                    3.473447
deposit_type                     -1.798965
required_car_parking_spaces      -1.397220
fe_has_previous_cancellations     1.051115
market_segment                    0.919749
fe_has_parking_request           -0.754086
fe_room_type_mismatch            -0.553665
lead_time                         0.545942
country                           0.503909
fe_has_booking_changes           -0.478832
distribution_channel             -0.474453
previous_bookings_not_canceled   -0.372467
fe_has_special_request           -0.342003
stays_in_week_nights              0.242434
fe_weekend_ratio                  0.239444
adr                               0.231036
total_of_special_requests        -0.204895
fe_total_nights                  -0.192926
booking_changes                   0.188482
fe_is_weekend_stay               -0.143720
is_repeated_guest                -0.115402
children                          0.106400
adults                            0.095499
assigned_room_type               -0.089904
days_in_waiting_list             -0.085214
fe_total_guests                  -0.061046
customer_type                    -0.049065
reserved_room_type                0.044638
babies                            0.035140
meal                              0.023105
stays_in_weekend_nights           0.016227
hotel                             0.010848
arrival_date_day_of_month        -0.004058
city                             -0.003442
previous_cancellations            0.002817
arrival_date_week_number         -0.002442
fe_season                         0.002074
arrival_date_month                0.001810
dtype: float64

In [89]:
y_pred = pipeline.predict(x_test_scaled)

y_proba = pipeline.predict_proba(
    x_test_scaled
)[:, 1]

In [90]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.83      0.80      0.81     15001
           1       0.68      0.72      0.70      8829

    accuracy                           0.77     23830
   macro avg       0.75      0.76      0.76     23830
weighted avg       0.77      0.77      0.77     23830

In [91]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_proba)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {roc_auc:.4f}")

Accuracy : 0.7709
Precision: 0.6800
Recall   : 0.7210
F1 Score : 0.6999
ROC-AUC  : 0.8589

# Random Forest

In [91]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel


# Tree-based feature selector
tree_selector = SelectFromModel(
    RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),
    threshold="median"
)


# Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)


# Pipeline
rf_pipeline_ = Pipeline([
    ("selector", tree_selector),
    ("sampler", SMOTE(random_state=42)),
    ("model", rf_model)
])


# Fit
rf_pipeline_.fit(
    x_train_scaled,
    y_train
)

Pipeline(steps=[('selector',
                 SelectFromModel(estimator=RandomForestClassifier(n_estimators=300,
                                                                  n_jobs=-1,
                                                                  random_state=42),
                                 threshold='median')),
                ('sampler', SMOTE(random_state=42)),
                ('model',
                 RandomForestClassifier(n_estimators=500, n_jobs=-1,
                                        random_state=42))])

In [92]:
selected_features_rf = x_train_scaled.columns[
    rf_pipeline_.named_steps["selector"].get_support()
].tolist()

print("Selected features:", len(selected_features_rf))
print(selected_features_rf)

Selected features: 19
['hotel', 'lead_time', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_week_nights', 'country', 'market_segment', 'deposit_type', 'customer_type', 'adr', 'total_of_special_requests', 'city', 'fe_total_nights', 'fe_weekend_ratio', 'fe_room_type_mismatch', 'fe_has_previous_cancellations', 'fe_has_deposit', 'fe_has_special_request']

In [93]:
y_pred_rf = rf_pipeline_.predict(x_test_scaled)

y_proba_rf = rf_pipeline_.predict_proba(
    x_test_scaled
)[:, 1]

In [ ]:
high_thr = 0.8
y_pred_high = (y_proba >= high_thr).astype(int)

# Random Forest + RandomSearch

In [94]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [110]:
rf_pipeline = Pipeline([
    (
        "selector",
        SelectFromModel(
            RandomForestClassifier(
                n_estimators=100,
                random_state=42,
                n_jobs=-1
            ),
            threshold="median"
        )
    ),

    (
        "sampler",
        SMOTE(random_state=42)
    ),

    (
        "model",
        RandomForestClassifier(
            random_state=42,
            n_jobs=-1
        )
    )
])

In [111]:
param_dist = {
    "model__n_estimators": [100, 200, 300, 500],
    "model__max_depth": [None, 10, 15, 20],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2"]
}

In [112]:
search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_dist,
    n_iter=15,
    scoring="f1",
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

In [113]:
search.fit(
    x_train_scaled,
    y_train
)

Fitting 3 folds for each of 15 candidates, totalling 45 fits
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=  22.3s
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=  23.0s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=  31.1s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=  32.1s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=  32.3s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  34.2s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  34.4s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  34.5s
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=  21.7s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=  28.8s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=  29.6s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=  29.7s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  44.9s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  33.9s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  44.8s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  44.3s

/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  37.2s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=  22.7s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  35.7s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=  22.6s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=  44.4s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=  44.7s
[CV] END model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=  26.7s
[CV] END model__max_depth=10, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=  30.0s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=  43.6s
[CV] END model__max_depth=10, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=  29.1s
[CV] END model__max_depth=10, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=  26.6s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time=  55.7s
[CV] END model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  45.2s
[CV] END model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  46.2s
[CV] END model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  46.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=  37.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=  42.8s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time=  59.8s
[CV] END model__max_depth=15, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time=  59.5s
[CV] END model__max_depth=10, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=  21.1s
[CV] END model__max_depth=10, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=  21.1s
[CV] END model__max_depth=10, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=  21.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=  34.3s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=  21.7s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=  24.1s
[CV] END model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=  23.8s
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=500; total time=  48.9s
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=500; total time=  43.9s
[CV] END model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=500; total time=  42.5s

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('selector',
                                              SelectFromModel(estimator=RandomForestClassifier(n_jobs=-1,
                                                                                               random_state=42),
                                                              threshold='median')),
                                             ('sampler',
                                              SMOTE(random_state=42)),
                                             ('model',
                                              RandomForestClassifier(n_jobs=-1,
                                                                     random_state=42))]),
                   n_iter=15, n_jobs=-1,
                   param_distributions={'model__max_depth': [None, 10, 15, 20],
                                        'model__max_features': ['sqrt', 'log2'],
                                        'model__min_samples_leaf': [1, 2, 4],
                                        'model__min_samples_split': [2, 5, 10],
                                        'model__n_estimators': [100, 200, 300,
                                                                500]},
                   random_state=42, scoring='f1', verbose=2)

In [114]:
print("Best Parameters:")
print(search.best_params_)

print("\nBest CV F1:")
print(search.best_score_)

Best Parameters:
{'model__n_estimators': 300, 'model__min_samples_split': 5, 'model__min_samples_leaf': 1, 'model__max_features': 'log2', 'model__max_depth': None}

Best CV F1:
0.7891047510939407

In [115]:
best_rf = search.best_estimator_

In [116]:
best_rf

Pipeline(steps=[('selector',
                 SelectFromModel(estimator=RandomForestClassifier(n_jobs=-1,
                                                                  random_state=42),
                                 threshold='median')),
                ('sampler', SMOTE(random_state=42)),
                ('model',
                 RandomForestClassifier(max_features='log2',
                                        min_samples_split=5, n_estimators=300,
                                        n_jobs=-1, random_state=42))])

In [117]:
y_pred_rf_h = best_rf.predict(x_test_scaled)
y_proba_rf_h = best_rf.predict_proba(x_test_scaled)[:, 1]

# Extra trees

In [103]:
from sklearn.ensemble import ExtraTreesClassifier

et_selector = SelectFromModel(
    ExtraTreesClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),
    threshold="median"
)

et_model = ExtraTreesClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

et_pipeline = Pipeline([
    ("selector", et_selector),
    ("sampler", SMOTE(random_state=42)),
    ("model", et_model)
])

et_pipeline.fit(
    x_train_scaled,
    y_train
)

Pipeline(steps=[('selector',
                 SelectFromModel(estimator=ExtraTreesClassifier(n_estimators=300,
                                                                n_jobs=-1,
                                                                random_state=42),
                                 threshold='median')),
                ('sampler', SMOTE(random_state=42)),
                ('model',
                 ExtraTreesClassifier(n_estimators=500, n_jobs=-1,
                                      random_state=42))])

In [104]:
selected_features_et = x_train_scaled.columns[
    et_pipeline.named_steps["selector"].get_support()
].tolist()

print("Selected features:", len(selected_features_et))
print(selected_features_et)

Selected features: 19
['hotel', 'lead_time', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_week_nights', 'country', 'market_segment', 'deposit_type', 'customer_type', 'adr', 'total_of_special_requests', 'city', 'fe_season', 'fe_total_nights', 'fe_room_type_mismatch', 'fe_has_previous_cancellations', 'fe_has_deposit', 'fe_has_special_request']

In [105]:
y_pred_et = et_pipeline.predict(x_test_scaled)

y_proba_et = et_pipeline.predict_proba(
    x_test_scaled
)[:, 1]

# Extra tree + Random Search

In [122]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import RandomizedSearchCV

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [123]:
et_pipeline_h = Pipeline([
    (
        "selector",
        SelectFromModel(
            ExtraTreesClassifier(
                n_estimators=100,
                random_state=42,
                n_jobs=-1
            ),
            threshold="median"
        )
    ),

    (
        "sampler",
        SMOTE(random_state=42)
    ),

    (
        "model",
        ExtraTreesClassifier(
            random_state=42,
            n_jobs=-1
        )
    )
])

In [124]:
param_dist_et = {
    "model__n_estimators": [100, 200, 300, 500],

    "model__max_depth": [
        None, 10, 15, 20, 30
    ],

    "model__min_samples_split": [
        2, 5, 10
    ],

    "model__min_samples_leaf": [
        1, 2, 4
    ],

    "model__max_features": [
        "sqrt", "log2", None
    ],

    "model__criterion": [
        "gini", "entropy", "log_loss"
    ],

    "model__class_weight": [
        None, "balanced"
    ]
}

In [125]:
et_search = RandomizedSearchCV(
    estimator=et_pipeline_h,
    param_distributions=param_dist_et,
    n_iter=15,
    scoring="f1",
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

In [126]:
et_search.fit(
    x_train_scaled,
    y_train
)

Fitting 3 folds for each of 15 candidates, totalling 45 fits
[CV] END model__class_weight=None, model__criterion=entropy, model__max_depth=15, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  32.0s
[CV] END model__class_weight=None, model__criterion=entropy, model__max_depth=15, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  32.9s
[CV] END model__class_weight=None, model__criterion=entropy, model__max_depth=15, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  33.3s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  45.6s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  46.3s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  46.6s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  53.8s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  54.4s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  43.8s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  44.2s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  28.2s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  43.2s

/Users/asadbek/Documents/machine-learning/hotel_bookings/myenv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=None, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  59.6s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time=  58.4s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  28.3s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time=  59.2s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=20, model__max_features=log2, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=  28.5s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=500; total time= 1.0min
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=  38.1s
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=  34.2s
[CV] END model__class_weight=balanced, model__criterion=entropy, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  30.6s
[CV] END model__class_weight=balanced, model__criterion=entropy, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  32.1s
[CV] END model__class_weight=balanced, model__criterion=entropy, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=  31.7s
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=None, model__max_features=sqrt, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=  39.2s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=30, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  35.6s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=30, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  33.4s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  26.3s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  27.3s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=30, model__max_features=sqrt, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=  36.0s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=10, model__max_features=log2, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=  28.2s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  38.3s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  38.1s
[CV] END model__class_weight=None, model__criterion=gini, model__max_depth=20, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=  37.6s
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=20, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time= 1.4min
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=20, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time= 1.7min
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time= 1.5min
[CV] END model__class_weight=None, model__criterion=log_loss, model__max_depth=20, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time= 1.7min
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time= 1.6min
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=30, model__max_features=log2, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time= 1.5min
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time=  59.4s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time=  58.5s
[CV] END model__class_weight=balanced, model__criterion=log_loss, model__max_depth=15, model__max_features=sqrt, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=500; total time=  58.6s
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=30, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=500; total time= 2.7min
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=30, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=500; total time= 2.7min
[CV] END model__class_weight=balanced, model__criterion=gini, model__max_depth=30, model__max_features=None, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=500; total time= 2.6min

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('selector',
                                              SelectFromModel(estimator=ExtraTreesClassifier(n_jobs=-1,
                                                                                             random_state=42),
                                                              threshold='median')),
                                             ('sampler',
                                              SMOTE(random_state=42)),
                                             ('model',
                                              ExtraTreesClassifier(n_jobs=-1,
                                                                   random_state=42))]),
                   n_iter=15, n_jobs=-1,
                   param_distributions={'model__class_weight': [None,
                                                                'balanced'],
                                        'model__criterion': ['gini', 'entropy',
                                                             'log_loss'],
                                        'model__max_depth': [None, 10, 15, 20,
                                                             30],
                                        'model__max_features': ['sqrt', 'log2',
                                                                None],
                                        'model__min_samples_leaf': [1, 2, 4],
                                        'model__min_samples_split': [2, 5, 10],
                                        'model__n_estimators': [100, 200, 300,
                                                                500]},
                   random_state=42, scoring='f1', verbose=2)

In [127]:
print("Best Parameters:")
print(et_search.best_params_)

print("\nBest CV F1:")
print(et_search.best_score_)

Best Parameters:
{'model__n_estimators': 500, 'model__min_samples_split': 10, 'model__min_samples_leaf': 1, 'model__max_features': None, 'model__max_depth': 30, 'model__criterion': 'gini', 'model__class_weight': 'balanced'}

Best CV F1:
0.7911831223116762

In [128]:
best_et = et_search.best_estimator_

In [129]:
y_pred_et = best_et.predict(x_test_scaled)

y_proba_et = best_et.predict_proba(
    x_test_scaled
)[:, 1]

In [92]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

models = {
    "Logistic Regression": pipeline,
    "Random Forest H": best_rf,
    "Random Forest": rf_pipeline_,
    "Extra Trees H": best_et,
    "Extra Trees": et_pipeline,
}

for name, pipeline in models.items():

    # Prediction
    y_pred = pipeline.predict(x_test_scaled)

    # Probability for ROC-AUC
    y_proba = pipeline.predict_proba(x_test_scaled)[:, 1]

    # Precision
    high_thr = 0.8
    y_pred_high = (y_proba >= high_thr).astype(int)

    # Metrics
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred_high),
        "Precision": precision_score(y_test, y_pred_high),
        "Recall": recall_score(y_test, y_pred_high),
        "F1 Score": f1_score(y_test, y_pred_high),
        "ROC-AUC": roc_auc_score(y_test, y_proba)
    })

results_df = pd.DataFrame(results)

results_df

NameError: name 'best_rf' is not defined